@extends('layouts.app')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-3">
    <h2>Reports</h2>
</div>

<div class="card p-4 mb-4">
    <h5>Generate Summary Report</h5>
    <form action="{{ route('reports.generate') }}" method="POST" class="d-flex gap-3 align-items-end">
        @csrf
        <div class="flex-grow-1">
            <label>Select Payout Cycle</label>
            <select name="cycle_id" class="form-control" required>
                <option value="">-- Select Cycle --</option>
                @foreach($cycles as $cycle)
                    <option value="{{ $cycle->id }}">{{ $cycle->cycle_name }}</option>
                @endforeach
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Generate</button>
    </form>
</div>

<h5>Previously Generated Reports</h5>
<table class="table table-bordered table-striped">
    <thead class="table-dark">
        <tr>
            <th>Cycle</th>
            <th>Type</th>
            <th>Generated By</th>
            <th>Generated At</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @forelse($reports as $report)
        <tr>
            <td>{{ $report->cycle->cycle_name ?? '—' }}</td>
            <td>{{ $report->report_type }}</td>
            <td>{{ $report->generator->name ?? '—' }}</td>
            <td>{{ $report->generated_at }}</td>
            <td>
                <a href="{{ route('reports.show', $report) }}" class="btn btn-sm btn-info">View</a>
                <form action="{{ route('reports.destroy', $report) }}" method="POST" class="d-inline"
                    onsubmit="return confirm('Delete this report?')">
                    @csrf @method('DELETE')
                    <button class="btn btn-sm btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        @empty
        <tr><td colspan="5" class="text-center">No reports generated yet.</td></tr>
        @endforelse
    </tbody>
</table>
{{ $reports->links() }}
@endsection