@extends('layouts.app')
@section('topbar-title', 'Reports')
@section('content')

<div class="page-head">
    <div>
        <div class="page-eyebrow">Insights</div>
        <h2 class="page-title">Reports</h2>
        <div class="page-sub">Generate and review cycle summary reports.</div>
    </div>
</div>

<div class="surface mb-3">
    <div class="surface-head">
        <h5>Generate summary report</h5>
    </div>
    <div class="surface-body">
        <form action="{{ route('reports.generate') }}" method="POST" class="d-flex flex-wrap gap-2 align-items-end">
            @csrf
            <div class="flex-grow-1" style="min-width: 280px;">
                <label class="form-label" for="cycle_id">Payout cycle</label>
                <select name="cycle_id" id="cycle_id" class="form-select" required>
                    <option value="">Select cycle</option>
                    @foreach($cycles as $cycle)
                        <option value="{{ $cycle->id }}">{{ $cycle->cycle_name }}</option>
                    @endforeach
                </select>
            </div>
            <button type="submit" class="btn btn-primary">
                <i class="bi bi-file-earmark-bar-graph me-1"></i> Generate report
            </button>
        </form>
    </div>
</div>

<div class="surface">
    <div class="surface-head">
        <h5>Previously generated</h5>
    </div>
    <table class="table mb-0">
        <thead>
            <tr>
                <th>Cycle</th>
                <th>Type</th>
                <th>Generated by</th>
                <th>Generated at</th>
                <th class="text-end">Actions</th>
            </tr>
        </thead>
        <tbody>
            @forelse($reports as $report)
                <tr>
                    <td class="fw-semibold">{{ $report->cycle->cycle_name ?? '—' }}</td>
                    <td><span class="pill pill-info">{{ $report->report_type }}</span></td>
                    <td>{{ $report->generator->name ?? '—' }}</td>
                    <td class="text-muted">{{ $report->generated_at }}</td>
                    <td class="text-end">
                        <div class="row-actions">
                            <a href="{{ route('reports.show', $report) }}" class="row-action view" title="View"><i class="bi bi-eye"></i></a>
                            <form action="{{ route('reports.destroy', $report) }}" method="POST"
                                onsubmit="return confirm('Delete this report?')" class="d-inline">
                                @csrf @method('DELETE')
                                <button type="submit" class="row-action delete" title="Delete"><i class="bi bi-trash"></i></button>
                            </form>
                        </div>
                    </td>
                </tr>
            @empty
                <tr><td colspan="5" class="table-empty">No reports generated yet.</td></tr>
            @endforelse
        </tbody>
    </table>
</div>

<div class="mt-3">
    {{ $reports->links() }}
</div>
@endsection
